# Generated by Django 6.0.3 on 2026-07-03 04:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical / Dangerous'), ('MODERATE', 'Moderate'), ('LOW', 'Low')], db_index=True, max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemThreshold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disease_compliance_threshold_percent', models.PositiveIntegerField(default=50, help_text='Reporting Compliance Alert Threshold (Diseases), as a percentage.')),
                ('failed_login_attempts_threshold', models.PositiveIntegerField(default=8, help_text='Failed Login Attempts Threshold.')),
                ('system_error_threshold', models.PositiveIntegerField(default=50, help_text='System Error Threshold, count of errors.')),
                ('inactive_facility_threshold_days', models.PositiveIntegerField(default=7, help_text='Inactive Facility Alert Threshold, in days.')),
                ('high_usage_threshold_users', models.PositiveIntegerField(default=200, help_text='High System Usage Alert Threshold, count of active users.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
