# Generated by Django 6.0.3 on 2026-03-20 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditlog'),
        ('facilities', '0003_facility_suspended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='facilities.facility'),
        ),
    ]
