# Generated by Django 6.0.3 on 2026-03-30 21:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_address_user_city_user_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationReadStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('audit_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='core.auditlog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('audit_log', 'user')},
            },
        ),
    ]
