# Generated by Django 6.0.3 on 2026-05-07 05:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_patientprofile'),
        ('maternal_care', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='birth_episode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newborns', to='maternal_care.maternalcareepisode'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='mother',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PATIENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
