# Generated by Django 6.0.3 on 2026-05-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_patientprofile_blood_group_patientprofile_genotype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'State Admin'), ('FACILITY_IT_ADMIN', 'Facility IT Admin'), ('OFFICER_IN_CHARGE', 'Officer In Charge (OIC)'), ('DOCTOR', 'Doctor'), ('PHARMACIST', 'Pharmacist'), ('LAB_TECHNICIAN', 'Laboratory Technician'), ('NURSE', 'Nurse'), ('CHEW', 'Community Health Extension Worker'), ('PATIENT', 'Patient')], default='PATIENT', max_length=20),
        ),
    ]
