# Generated by Django 6.0.3 on 2026-06-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, help_text='e.g., Mother, Father, Aunt', max_length=100, null=True),
        ),
    ]
