# Generated by Django 6.0.3 on 2026-07-16 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_errorlog_failedloginattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='birth_status',
            field=models.CharField(blank=True, choices=[('ALIVE', 'Alive'), ('ADMITTED', 'Admitted'), ('DEAD', 'Dead')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='complications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='delivery_mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
