# Generated by Django 6.0.3 on 2026-05-07 05:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0003_appointment_priority_alter_appointment_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaternalCareEpisode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('episode_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('sequence_number', models.BigIntegerField(blank=True, db_index=True, editable=False, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active (Pregnant)'), ('DELIVERED', 'Delivered'), ('CLOSED', 'Closed / Postpartum Complete'), ('MISCARRIAGE', 'Miscarriage / Loss')], default='ACTIVE', max_length=20)),
                ('last_menstrual_period', models.DateField(blank=True, null=True)),
                ('expected_date_of_delivery', models.DateField(blank=True, null=True)),
                ('gravida', models.PositiveIntegerField(default=1, help_text='Total number of pregnancies')),
                ('parity', models.PositiveIntegerField(default=0, help_text='Number of previous births')),
                ('living_children', models.PositiveIntegerField(default=0)),
                ('partner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='pregnancies', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ANCVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_type', models.CharField(choices=[('NEW', 'New'), ('RETURN', 'Return')], default='NEW', max_length=10)),
                ('hiv_status', models.CharField(blank=True, max_length=50, null=True)),
                ('vdrl_syphilis', models.CharField(blank=True, max_length=50, null=True)),
                ('hepatitis_b', models.CharField(blank=True, max_length=50, null=True)),
                ('hemoglobin', models.DecimalField(blank=True, decimal_places=2, help_text='g/dL', max_digits=5, null=True)),
                ('urinalysis', models.TextField(blank=True, null=True)),
                ('tt_dose_given', models.CharField(blank=True, help_text='e.g. TT1, TT2', max_length=20, null=True)),
                ('iptp_dose_given', models.CharField(blank=True, help_text='e.g. Dose 1, Dose 2', max_length=20, null=True)),
                ('iron_folate_given', models.BooleanField(default=False)),
                ('risk_factors', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anc_record', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anc_visits', to='maternal_care.maternalcareepisode')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PNCVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_type', models.CharField(choices=[('NEW', 'New'), ('RETURN', 'Return')], default='NEW', max_length=10)),
                ('timing_of_visit', models.CharField(help_text='e.g., Within 24h, 3 Days, 7 Days, 6 Weeks', max_length=50)),
                ('vaginal_examination_conducted', models.BooleanField(default=False)),
                ('hemoglobin_pcv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('urinalysis', models.TextField(blank=True, null=True)),
                ('counselling_topics', models.JSONField(blank=True, default=list, help_text='List of topics covered')),
                ('outcome', models.CharField(choices=[('TREATED', 'Treated'), ('ADMITTED', 'Admitted'), ('REFERRED', 'Referred Out')], default='TREATED', max_length=50)),
                ('referral_reason', models.TextField(blank=True, null=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pnc_record', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pnc_visits', to='maternal_care.maternalcareepisode')),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PNCNewbornAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('cord_care_assessed', models.BooleanField(default=False)),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, help_text='Celsius (°C)', max_digits=4, null=True)),
                ('exclusive_breastfeeding', models.CharField(blank=True, help_text='Yes, No, Struggling', max_length=50, null=True)),
                ('newborn_danger_signs', models.JSONField(blank=True, default=list)),
                ('neonatal_jaundice', models.BooleanField(default=False)),
                ('first_dose_antibiotics_given', models.BooleanField(default=False)),
                ('kmc_provided', models.BooleanField(default=False)),
                ('outcome', models.CharField(choices=[('HEALTHY', 'Healthy / Discharged'), ('ADMITTED', 'Admitted to NICU'), ('REFERRED', 'Referred Out')], default='HEALTHY', max_length=20)),
                ('baby', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='pnc_assessments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pnc_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newborn_assessments', to='maternal_care.pncvisit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
