# Generated by Django 6.0.3 on 2026-06-14 15:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maternal_care', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ancvisit',
            name='next_visit_date',
            field=models.DateField(blank=True, help_text='Calculated date for the next visit', null=True),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='recommended_tasks',
            field=models.JSONField(blank=True, default=list, help_text='Tasks (like Ultrasound) due for THIS visit'),
        ),
        migrations.AddField(
            model_name='ancvisit',
            name='visit_sequence_number',
            field=models.PositiveIntegerField(default=1, help_text='Which visit in the sequence is this?'),
        ),
        migrations.AddField(
            model_name='maternalcareepisode',
            name='custom_anc_schedule',
            field=models.JSONField(blank=True, help_text="Overrides the Global ANC rule. Format: {'rule_type': '...', 'intervals_sequence': [], 'visit_tasks': {}}", null=True),
        ),
        migrations.AddField(
            model_name='maternalcareepisode',
            name='custom_pnc_schedule',
            field=models.JSONField(blank=True, help_text='Overrides the Global PNC rule. Same format.', null=True),
        ),
        migrations.AddField(
            model_name='pncvisit',
            name='next_visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pncvisit',
            name='recommended_tasks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='pncvisit',
            name='visit_sequence_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ancvisit',
            name='iptp_dose_given',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ancvisit',
            name='tt_dose_given',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='MaternalScheduleRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('care_type', models.CharField(choices=[('ANC', 'Antenatal Care'), ('PNC', 'Postnatal Care')], help_text='One active rule per care type.', max_length=10, unique=True)),
                ('rule_type', models.CharField(choices=[('ONCE', 'Once'), ('RECURRING', 'Recurring (Fixed Interval)'), ('VARIABLE_SEQUENCE', 'Variable Sequence')], default='VARIABLE_SEQUENCE', max_length=20)),
                ('interval_days', models.PositiveIntegerField(default=0, help_text='Used if RECURRING (e.g., every 30 days)')),
                ('intervals_sequence', models.JSONField(blank=True, default=list, help_text='Used if VARIABLE. Array of days between visits. e.g., [28, 28, 14, 14, 7]')),
                ('visit_tasks', models.JSONField(blank=True, default=dict, help_text="Map of visit sequence index to list of tasks. e.g., {'0': ['Booking Bloods', 'Dating Scan'], '4': ['Anomaly Scan']}")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
