# Generated by Django 6.0.3 on 2026-06-13 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_drug_created_by_remove_drug_deleted_by_and_more'),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='inventory_deducted',
            field=models.BooleanField(default=False, help_text='Flags if the linked item has been deducted from stock.'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='linked_item',
            field=models.ForeignKey(blank=True, help_text='The specific test kit or consumable used for this test.', limit_choices_to={'inventory_category__in': ['LAB_EQUIPMENT', 'CONSUMABLE']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_lab_tests', to='inventory.inventoryitem'),
        ),
    ]
