# Generated by Django 6.0.3 on 2026-03-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_it_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
