# Generated by Django 6.0.3 on 2026-05-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_facility_suspended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='ward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
