# Generated by Django 6.0.3 on 2026-05-07 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0004_alter_appointment_visit_type'),
        ('facilities', '0003_facility_suspended_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('referral_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('sequence_number', models.BigIntegerField(blank=True, db_index=True, editable=False, null=True)),
                ('referral_type', models.CharField(choices=[('PHYSICAL', 'Physical'), ('TELEMEDICINE', 'Telemedicine'), ('EMERGENCY', 'Emergency')], default='PHYSICAL', max_length=20)),
                ('reason_for_referral', models.TextField()),
                ('clinical_summary', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='all_referrals', to=settings.AUTH_USER_MODEL)),
                ('receiving_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inbound_referrals', to='facilities.facility')),
                ('referred_by', models.ForeignKey(help_text='Staff who initiated this', on_delete=django.db.models.deletion.PROTECT, related_name='authored_referrals', to=settings.AUTH_USER_MODEL)),
                ('referring_facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outbound_referrals', to='facilities.facility')),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
