# Generated by Django 6.0.3 on 2026-06-14 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('facilities', '0004_facility_ward'),
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='destination_level',
            field=models.CharField(choices=[('PRIMARY', 'Primary Health Care (Internal)'), ('SECONDARY', 'Secondary Health Care'), ('HIGHER', 'Higher Health Care'), ('OTHER', 'Other')], default='PRIMARY', max_length=20),
        ),
        migrations.AddField(
            model_name='referral',
            name='email_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='email_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='mode_of_referral',
            field=models.CharField(blank=True, choices=[('SOFTCOPY', 'Softcopy (Email/Digital)'), ('HARDCOPY', 'Hardcopy (Physical Document)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='mode_of_transportation',
            field=models.CharField(blank=True, choices=[('PRIVATE', 'Private Vehicle'), ('AMBULANCE', 'Ambulance'), ('PUBLIC', 'Public Transportation'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='receiving_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_referrals', to='departments.department'),
        ),
        migrations.AddField(
            model_name='referral',
            name='target_department_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='target_doctor_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='receiving_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inbound_referrals', to='facilities.facility'),
        ),
    ]
