# Generated by Django 6.0.3 on 2026-07-16 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0003_telemedicinesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemedicinesession',
            name='participants',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CALL_CREATED', 'Call Created'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
