# Generated by Django 6.0.3 on 2026-07-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adverse_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adverseevent',
            name='closed_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='reported_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='resolved_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adverseevent',
            name='under_review_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
