# Generated by Django 6.0.3 on 2026-07-03 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='diagnosed_disease',
            field=models.ForeignKey(blank=True, help_text='Structured link to the global disease registry, used for outbreak/severity alerting.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to='registry.disease'),
        ),
    ]
