# Generated by Django 6.0.3 on 2026-07-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_diagnosed_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='presenting_complaint',
            field=models.TextField(blank=True, null=True),
        ),
    ]
