# Generated by Django 6.0.3 on 2026-06-13 23:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_facility_ward'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='restored_by',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='drugbatch',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='drugbatch',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='drugbatch',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='drugbatch',
            name='restored_by',
        ),
        migrations.RemoveField(
            model_name='drugbatch',
            name='updated_by',
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('inventory_category', models.CharField(choices=[('DRUG', 'Drug / Medication'), ('LAB_EQUIPMENT', 'Laboratory Equipment'), ('CONSUMABLE', 'General Consumable')], default='DRUG', max_length=20)),
                ('drug_classification', models.CharField(blank=True, choices=[('NORMAL', 'Normal Medication'), ('IMMUNIZATION', 'Immunization / Vaccine')], max_length=20, null=True)),
                ('item_type', models.CharField(help_text='e.g., Tablets, Vials, Pieces, Packs', max_length=50)),
                ('global_threshold', models.PositiveIntegerField(default=10, help_text='Level to trigger Low Stock warning')),
                ('schedule_rules', models.JSONField(blank=True, help_text='JSON defining the dosage intervals. Leave null if not applicable.', null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='facilities.facility')),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ItemBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('batch_number', models.CharField(max_length=100)),
                ('initial_quantity', models.PositiveIntegerField()),
                ('remaining_quantity', models.PositiveIntegerField()),
                ('purchased_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(max_length=255)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.inventoryitem')),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.itembatch'),
        ),
    ]
