# Generated by Django 6.0.3 on 2026-06-13 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('immunization', '0003_alter_immunizationrecord_vaccine_given'),
        ('inventory', '0002_remove_drug_created_by_remove_drug_deleted_by_and_more'),
        ('prescriptions', '0002_remove_prescriptionitem_drug_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Drug',
        ),
        migrations.DeleteModel(
            name='DrugBatch',
        ),
    ]
