# Generated by Django 6.0.3 on 2026-06-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_delete_drug_delete_drugbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='threshold_type',
            field=models.CharField(choices=[('ABSOLUTE', 'Absolute Quantity'), ('PERCENTAGE', 'Percentage of Initial Stock')], default='ABSOLUTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='global_threshold',
            field=models.PositiveIntegerField(default=10, help_text='If type is ABSOLUTE, this is exact quantity. If PERCENTAGE, this is 1-100.'),
        ),
    ]
