# Generated by Django 6.0.3 on 2026-06-13 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_drug_created_by_remove_drug_deleted_by_and_more'),
        ('prescriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptionitem',
            name='drug',
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, help_text='Links directly to the generalized Inventory Item.', limit_choices_to={'inventory_category': 'DRUG'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_items', to='inventory.inventoryitem'),
        ),
    ]
