# Generated by Django 6.0.3 on 2026-06-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_remove_prescriptionitem_drug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='route',
            field=models.CharField(default='Oral', help_text='e.g., Oral, Intravenous (IV), Intramuscular (IM), Topical', max_length=100),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='special_instructions',
            field=models.TextField(blank=True, help_text='Specific instructions for this exact medication (e.g., Take with food)', null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(blank=True, help_text='General instructions for the pharmacist or patient for the overall prescription', null=True),
        ),
    ]
