# Generated by Django 6.0.3 on 2026-07-02 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_prescriptionitem_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of units (tablets, vials, etc.) to dispense for this item'),
        ),
    ]
