# Generated by Django 6.0.3 on 2026-07-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0004_prescriptionitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='dispensed_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Number of units that have actually been dispensed so far'),
        ),
    ]
