# Generated by Django 6.0.3 on 2026-05-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_priority_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='visit_type',
            field=models.CharField(choices=[('GENERAL', 'General Consultation'), ('FOLLOW_UP', 'Follow-up'), ('ANTENATAL', 'Antenatal Care'), ('POSTNATAL', 'Postnatal Care'), ('IMMUNIZATION', 'Immunization'), ('EMERGENCY', 'Emergency'), ('OTHER', 'Other')], default='GENERAL', max_length=20),
        ),
    ]
