# Generated by Django 6.0.3 on 2026-07-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_visit_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='visit_type',
            field=models.CharField(choices=[('GENERAL', 'General Consultation'), ('FOLLOW_UP', 'Follow-up'), ('ANTENATAL', 'Antenatal Care'), ('POSTNATAL', 'Postnatal Care'), ('IMMUNIZATION', 'Immunization'), ('EMERGENCY', 'Emergency'), ('COMMUNITY', 'Community Visit'), ('OTHER', 'Other')], default='GENERAL', max_length=20),
        ),
    ]
