# Generated by Django 6.0.3 on 2026-07-17 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_visit_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='assigned_for_vitals',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['NURSE', 'CHEW', 'DOCTOR']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vitals_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
