# Generated by Django 6.0.3 on 2026-05-07 03:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0003_appointment_priority_alter_appointment_status'),
        ('facilities', '0003_facility_suspended_at'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImmunizationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('session_type', models.CharField(choices=[('FIXED', 'Fixed (In-Facility)'), ('OUTREACH', 'Outreach'), ('MOBILE', 'Mobile')], default='FIXED', max_length=20)),
                ('state', models.CharField(max_length=100)),
                ('lga', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('site_name', models.CharField(blank=True, help_text='Required for Outreach/Mobile', max_length=255, null=True)),
                ('date_of_visit', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('MISSED', 'Missed')], default='COMPLETED', max_length=20)),
                ('age_at_vaccination', models.CharField(blank=True, help_text="e.g., '6 Weeks', '9 Months'", max_length=50, null=True)),
                ('reporting_month', models.IntegerField(editable=False)),
                ('reporting_year', models.IntegerField(editable=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('administered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_vaccines', to=settings.AUTH_USER_MODEL)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunization_records', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immunizations', to='facilities.facility')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='immunizations', to=settings.AUTH_USER_MODEL)),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vaccine_given', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vaccinations', to='inventory.drug')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
