# Generated by Django 6.0.3 on 2026-06-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immunization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='immunizationrecord',
            name='dose_number',
            field=models.PositiveIntegerField(default=1, help_text='Which dose in the sequence this was.'),
        ),
        migrations.AddField(
            model_name='immunizationrecord',
            name='next_due_date',
            field=models.DateField(blank=True, help_text='Calculated automatically by the ScheduleEngine', null=True),
        ),
        migrations.AlterField(
            model_name='immunizationrecord',
            name='age_at_vaccination',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
