# Generated by Django 6.0.3 on 2026-06-13 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('immunization', '0002_immunizationrecord_dose_number_and_more'),
        ('inventory', '0002_remove_drug_created_by_remove_drug_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='immunizationrecord',
            name='vaccine_given',
            field=models.ForeignKey(limit_choices_to={'drug_classification': 'IMMUNIZATION'}, on_delete=django.db.models.deletion.PROTECT, related_name='vaccinations', to='inventory.inventoryitem'),
        ),
    ]
