# Generated by Django 6.0.3 on 2026-07-16 19:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_chew', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthpromotion',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role__in': ['CHEW', 'NURSE', 'DOCTOR']}, related_name='assigned_health_promotions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='healthpromotion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthpromotion',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthpromotion',
            name='expected_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthpromotion',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='healthpromotion',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthpromotion',
            name='target_audience',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='healthpromotion',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='healthpromotion',
            name='type',
            field=models.CharField(blank=True, choices=[('AWARENESS', 'Awareness'), ('VACCINATION_DRIVE', 'Vaccination Drive'), ('SCREENING', 'Screening'), ('EDUCATION', 'Education')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='postactivity',
            name='challenges',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postactivity',
            name='female_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postactivity',
            name='key_messages_delivered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postactivity',
            name='male_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postactivity',
            name='number_of_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postactivity',
            name='outcome_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
