# Generated by Django 6.0.3 on 2026-07-16 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse_chew', '0002_alter_healthpromotion_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthpromotion',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('role', 'PATIENT'), _negated=True), related_name='assigned_health_promotions', to=settings.AUTH_USER_MODEL),
        ),
    ]
